language: go

sudo: required

os:
  - linux
  - osx
  - windows

go:
  - 1.10.x
  - master

git:
  depth: 1

install: true

before_install:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - go test -v ./...

branches:
  only:
    - master